### ISSUE TITLE
Using images for board squares

### ISSUE THREAD

**Issue by ZenLearner** [oakmac/chessboardjs#120]
Hi,

By specifying an image on the css that controls the white and dark squares I was able to draw a nice board using the program pgn4web. For example http://chess.semprun.net or http://foundation.semprun.net In the following fashion:

```css
.whiteSquare {
  background-image: url(my-images/light3-60.jpg);
  width: 53;
  height: 53;
}

.highlightWhiteSquare {
  background-image: url(my-images/flickr-light-60.jpg);
  width: 53;
  height: 53;
}

.highlightBlackSquare {
  background-image: url(my-images/dark2-60.jpg);
  width: 53;
  height: 53;
}
```

This approach does not work with chessboard.(altering the css file chessboard.css for chessboard.black.square or for chessboard.white.square). Would it be possible to do similarly here? They have nice wood texture boards in ChessBase and Hiarcs, so I was trying to accomplish something similar...

Thx,
