### ISSUE TITLE
Suggestion: a chessboard config option for square color

### ISSUE THREAD

**Issue by justingolden21** [oakmac/chessboardjs#209]
### Suggestion: a chessboard config option for square color

Something like `whiteSquareColor: '#fff'`

For example:

```js
board = Chessboard('board', {
  position: 'start',
  whiteSquareColor: '#fff',
  blackSquareColor: '#000',
});
```

This feels like a very basic feature and one that shouldn't be handled by working *around* chessboard.js but rather handled by chessboard itself.

Thank you for listening to my feedback : )

**Comment by justingolden21** [comment]
Just found this: https://www.chessable.com/discussion/thread/198273/change-board-colour-css/

```css
.white-1e1d7{background-color:#b0b9b4 !important;color:#6d8873 !important}
.black-3c85d{background-color:#6d8873 !important;color:#b0b9b4 !important}
```

![image](https://user-images.githubusercontent.com/30274440/109376129-3e80c580-7877-11eb-8b03-da6e88d5a9ff.png)
